name: CI

on:
  push:
    branches:
    - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build application
        run: ./gradlew assembleDebug

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
