name: CI

on:
  push:
    branches:
      - main
      - develop
      - ^feature\/[0-9]+$
  pull_request:
    branches:
      - main
      - develop
      - ^feature\/[0-9]+$

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Build application
        run: ./gradlew assembleDebug
      - name: Upload artifacts
        uses: actions/upload-artifact@v4